/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 20:13:43 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution0598;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution0598_ESTest extends Solution0598_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution0598 solution0598_0 = new Solution0598();
      int[][] intArray0 = new int[1][4];
      int[] intArray1 = new int[7];
      intArray1[0] = 718;
      intArray1[1] = 718;
      intArray0[0] = intArray1;
      int int0 = solution0598_0.maxCount(718, 718, intArray0);
      assertEquals(515524, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution0598 solution0598_0 = new Solution0598();
      int[][] intArray0 = new int[1][4];
      int[] intArray1 = new int[7];
      intArray1[1] = 718;
      intArray0[0] = intArray1;
      int int0 = solution0598_0.maxCount((-506), 718, intArray0);
      assertEquals((-363308), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution0598 solution0598_0 = new Solution0598();
      // Undeclared exception!
      try { 
        solution0598_0.maxCount(0, 0, (int[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution0598", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution0598 solution0598_0 = new Solution0598();
      int[][] intArray0 = new int[1][1];
      // Undeclared exception!
      try { 
        solution0598_0.maxCount(0, 0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("original.Solution0598", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution0598 solution0598_0 = new Solution0598();
      int[][] intArray0 = new int[1][4];
      int int0 = solution0598_0.maxCount(718, 718, intArray0);
      assertEquals(0, int0);
  }
}
