/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:23:34 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2459;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2459_ESTest extends Solution2459_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2459 solution2459_0 = new Solution2459();
      int[] intArray0 = new int[6];
      intArray0[5] = 2;
      int int0 = solution2459_0.sortArray(intArray0);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2459 solution2459_0 = new Solution2459();
      int[] intArray0 = new int[6];
      intArray0[0] = 2;
      int int0 = solution2459_0.sortArray(intArray0);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[1];
      Solution2459 solution2459_0 = new Solution2459();
      int int0 = solution2459_0.sortArray(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2459 solution2459_0 = new Solution2459();
      // Undeclared exception!
      try { 
        solution2459_0.sortArray((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2459", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution2459 solution2459_0 = new Solution2459();
      int[] intArray0 = new int[4];
      intArray0[2] = (-358);
      // Undeclared exception!
      try { 
        solution2459_0.sortArray(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -358 out of bounds for length 4
         //
         verifyException("original.Solution2459", e);
      }
  }
}
