/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:03:39 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2907;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2907_ESTest extends Solution2907_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[5];
      intArray0[1] = (-1);
      intArray0[3] = 192;
      int[] intArray1 = new int[7];
      intArray1[1] = 192;
      intArray1[3] = 192;
      int int0 = solution2907_0.maxProfit(intArray0, intArray1);
      assertEquals(384, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[5];
      intArray0[0] = (-1);
      int[] intArray1 = new int[7];
      int int0 = solution2907_0.maxProfit(intArray0, intArray1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      // Undeclared exception!
      try { 
        solution2907_0.maxProfit((int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2907", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[7];
      intArray0[2] = 1930;
      int[] intArray1 = new int[2];
      // Undeclared exception!
      try { 
        solution2907_0.maxProfit(intArray0, intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("original.Solution2907", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[3];
      intArray0[0] = 1;
      intArray0[1] = 2241;
      intArray0[2] = 2286;
      int int0 = solution2907_0.maxProfit(intArray0, intArray0);
      assertEquals(4528, int0);
  }
}
