/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:35:07 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2912;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2912_ESTest extends Solution2912_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[3];
      solution2912_0.numberOfWays(451, (-2098), 1040, intArray0, intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[7];
      // Undeclared exception!
      solution2912_0.numberOfWays(1574, 1574, 1000000007, intArray0, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[9];
      int[] intArray1 = new int[1];
      // Undeclared exception!
      try { 
        solution2912_0.numberOfWays(1, 0, 1, intArray0, intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("original.Solution2912", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[3];
      int[] intArray1 = new int[5];
      intArray1[0] = (-1378);
      intArray1[1] = (-1978);
      int int0 = solution2912_0.numberOfWays(2455, (-1978), (-1378), intArray0, intArray1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[7];
      intArray0[0] = (-521);
      intArray0[1] = (-521);
      int[] intArray1 = new int[4];
      intArray1[0] = (-521);
      int int0 = solution2912_0.numberOfWays(0, (-5523), (-521), intArray1, intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[3];
      int int0 = solution2912_0.numberOfWays(2455, 0, 0, intArray0, intArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      int[] intArray0 = new int[2];
      intArray0[0] = 1;
      int[] intArray1 = new int[2];
      int int0 = solution2912_0.numberOfWays(0, 0, 1, intArray0, intArray1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Solution2912 solution2912_0 = new Solution2912();
      // Undeclared exception!
      try { 
        solution2912_0.numberOfWays(0, 1, 49, (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2912", e);
      }
  }
}
